### ISSUE TITLE
All aio.FakeRedis instances share the same server

### ISSUE THREAD

**Issue by ijrsvt** [cunla/fakeredis-py#218]
**Describe the bug**

If I create two clients with `fakeredis.aioredis.FakeRedis()` (even with different hosts/ports) they share the same backend.

**To Reproduce**
```
from fakeredis.aioredis import FakeRedis as FakeAsyncRedis
FakeAsyncRedis(host="host_one", port=1000).set("30", "30")
assert FakeAsyncRedis(host="host_two", port=2000).get("30") is None
```
Raises an AssertionError

**Expected behavior**
```
from fakeredis import FakeRedis
FakeRedis(host="host_one", port=1000).set("30", "30")
assert FakeRedis(host="host_two", port=2000).get("30") is None
```

**Desktop (please complete the following information):**
 - OS: MacOS + Linux
 - python version: 3.7.11
 - redis-py version 2.17.0
```
$ pip list | grep redis
aioredis                                 1.3.1
fakeredis                                2.17.0
hiredis                                  2.1.0
redis                                    4.3.4
```

**Additional context**

**Comment by kamilglod** [comment]
We're having the same problem - bug was introduced in 2.17.0 - in previous version it works fine on our end. 
Maybe it's because of this change: https://github.com/cunla/fakeredis-py/pull/213/files#diff-288db5468d2e9d706d7767762175c8b7f73e00a2601114e0be0c42b43d8f2843L66-R66 - reusing some default port instead of creating new one each time.

**Comment by netrix** [comment]
I am afraid that this issue hasn't been fixed by above commit. The change in the place pointed by https://github.com/cunla/fakeredis-py/issues/218#issuecomment-1665096420 wasn't reversed. 

The problem still occurs in the newest version. Is this change of behavior done on purpose ?

**Comment by wenzhiTeo** [comment]
Changes related to https://github.com/cunla/fakeredis-py/commit/d22713828c25f8a825bff3f56e9ab11d59f1f3e1

Just to provide possible solution. I think that the default host value in `class FakeRedis(redis_async.Redis):` should be remove. To test the solution can just update `__init__` function with `kwargs["host"] = uuid.uuid4().hex`. Then will found that issue fixed.

![image](https://github.com/cunla/fakeredis-py/assets/99173738/148eab71-8ca6-4ff8-935b-2945ef02d763)


---

**For those facing the issue and need solution immediately**, may overrider the `__init__` function as below:

```Python
class CustomFakeStrictRedis(fakeredis.FakeStrictRedis):
    def __init__(self, *args, server=None, version=(7,), **kwargs):
        # To ensure the FakeStrictRedis not gonna sharing the same server
        if not server:
            server = fakeredis.FakeServer()

        super().__init__(*args, server=server, **kwargs)
```

Example case:
``` Python
class ConversationAllowedInboxViewQueryBaseTestCase(GraphQLTestCase):
    def setUp(self):
        super().setUp()
        self.loaders_get_redis_connection_patcher = patch(
            "xxx.loaders.get_redis_connection", CustomFakeStrictRedis
        )
        self.utils_get_redis_connection_patcher = patch(
            "xxxx.utils.get_redis_connection", CustomFakeStrictRedis
        )
        self.loaders_get_redis_connection_patcher.start()
        self.utils_get_redis_connection_patcher.start()


    def tearDown(self):
        super().tearDown()
        self.loaders_get_redis_connection_patcher.stop()
        self.utils_get_redis_connection_patcher.stop()

```

**Comment by danielm-cfa** [comment]
If you create two redis connections without supplying any connection parameters (host/port/...) it will use the defaults and therefore will use the same server.
FakeRedis mimiks this behavior, I am not sure I understand the issue...
Please provide a test?

**Comment by cunla** [comment]
If you create two redis connections without supplying any connection parameters (host/port/...) it will use the defaults and therefore will use the same server.

FakeRedis mimiks this behavior, I am not sure I understand the issue...

Please provide a test where you provide different connection parameteers and the result is two connection sharing the server instance.

**Comment by wenzhiTeo** [comment]
>If you create two redis connections without supplying any connection parameters (host/port/...) it will use the defaults and therefore will use the same server.

You are right. But for some cases we may not provide any connection parameters just like the example I provided. 

We might do 
``` Python
self.loaders_get_redis_connection_patcher = patch(
    "xxx.loaders.get_redis_connection", CustomFakeStrictRedis
)

# In patch we cannot pass initiated object
```
(Probably this is a rare case)

---

At `fakeredis 2.16.0` + `redis 5.0.0rc1` the creation of redis connections is independent 
- When no parameter passed
- connection parameters `host` & `port` not introduce yet


But in `fakeredis 2.20.0` +`redis 5.1.0a1` the creation of redis connections is identical 
- when no connection parameters provided
- This will messed the result between 2 redis
![image](https://github.com/cunla/fakeredis-py/assets/99173738/dca57675-6eae-480b-8d08-3f77bd1abdf9)

I suspect the reason is because the default value set in `aioredis.py::FakeRedis`. Then the default value might not needed
Because from the source code I notice that `_server.py::FakeRedisMixin::__init__` have ability to auto generate the unique or random `host` value with `kwargs.setdefault("host", uuid.uuid4().hex)`

---

**Probably this not an issue anymore, if current version of `fakeredis` is making `connection parameters` as required parameters for independent redis connections.** 

Which mean whenever independent redis connection is needed

We need to do this
```Python
from fakeredis.aioredis import FakeRedis as FakeAsyncRedis
x = FakeAsyncRedis(host="host_one", port=1000)
y = FakeAsyncRedis(host="host_two", port=2000)
```

instead of 

```Python
from fakeredis.aioredis import FakeRedis as FakeAsyncRedis
x = FakeAsyncRedis()
y = FakeAsyncRedis()
```

Then for that not going initialize the fake redis connection, will need to override the `__init__` function
