### ISSUE TITLE
Missing get_fake_connection

### ISSUE THREAD

**Issue by jlopespt** [cunla/fakeredis-py#261]
Got this error message:

> from fakeredis import get_fake_connection
> E   ImportError: cannot import name 'get_fake_connection' from 'fakeredis' (/usr/local/lib/python3.9/site-packages/fakeredis/__init__.py)

Noticed that this function was removed from the repository ([commit 888adc0](https://github.com/cunla/fakeredis-py/commit/888adc00a503ba55f340017990d4e60f6f813c5e)).

Was this intentional?
What is the alternative to it?

Many thanks for any feedback!

**Comment by cunla** [comment]
Hi,

I realized I needed to maintain this method whenever there were changes in django-rq, and I wanted to avoid it.
I still listed it in the documentation [here](https://fakeredis.readthedocs.io/en/latest/?h=django#use-to-test-django-rq). You can maintain this as part of your code (for me personally, I wanted the option of using `UNIX_SOCKET_PATH` instead of `URL`). 

It would be great if django-rq would have a `redis_cls` parameters.

Alternatively, if you don't want to maintain the logic for the override method, you can override `redis.Redis` and `redis.StrictRedis` before calling django-rq.

**Comment by cunla** [comment]
@jlopespt did you manage? can this be closed?

**Comment by jlopespt** [comment]
Hi @cunla yes, we adapted our code.
Thanks for the feedback and follow up!
